package web;

import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import jakarta.servlet.GenericServlet;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;

import model.SavingsAccount;
import service.Bank;

/**
 * Public "Bank Status" page.
 *
 * <p><b>Experiment 4 - GenericServlet:</b> Extends {@link GenericServlet}
 * and overrides the single protocol-independent {@code service()} method.
 * It does not care whether the request is GET or POST, which suits a
 * simple read-only information page.</p>
 *
 * <p>Lifecycle methods {@code init()} and {@code destroy()} are also shown.</p>
 *
 * Mapped to URL: <code>/bank-info</code> (no login needed)
 */
public class BankInfoServlet extends GenericServlet {

    private static final long serialVersionUID = 1L;

    private LocalDateTime startedAt;

    /** Called once when Tomcat loads the servlet. */
    @Override
    public void init() throws ServletException {
        startedAt = LocalDateTime.now();
        log("BankInfoServlet initialised at " + startedAt);
    }

    /** Handles every request (GET, POST, ...) in one method. */
    @Override
    public void service(ServletRequest request, ServletResponse response)
            throws ServletException, IOException {

        Bank bank = BankProvider.getBank(getServletContext());
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

        int count;
        double total;
        synchronized (bank) {
            count = bank.getAccountCount();
            total = bank.getTotalBalance();
        }

        response.setContentType("text/html;charset=UTF-8");
        PrintWriter out = response.getWriter();

        out.println("<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'>");
        out.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
        out.println("<meta name='description' content='Live status of NovaBank - served by a GenericServlet.'>");
        out.println("<title>Bank Status | NovaBank</title>");
        out.println("<link rel='stylesheet' href='css/style.css'></head><body>");
        out.println("<div class='bg-orbs'><span></span><span></span><span></span></div>");
        out.println("<main class='center-page'><section class='glass card info-card'>");
        out.println("<span class='badge'>Experiment 4 &middot; GenericServlet</span>");
        out.println("<h1 class='brand-title'>NovaBank Status</h1>");
        out.println("<p class='muted'>This page is generated by <code>GenericServlet.service()</code>.</p>");

        out.println("<div class='stat-grid'>");
        stat(out, "Server status", "<span class='dot-live'></span> Online");
        stat(out, "Open accounts", String.valueOf(count));
        stat(out, "Total deposits", String.format("Rs.%,.2f", total));
        stat(out, "Savings min. balance", String.format("Rs.%,.2f", SavingsAccount.getMinBalance()));
        stat(out, "Servlet started", startedAt.format(fmt));
        stat(out, "Server time", LocalDateTime.now().format(fmt));
        out.println("</div>");

        out.println("<p class='muted small'>Request protocol: " + request.getProtocol()
                + " &middot; Container: " + escape(getServletContext().getServerInfo()) + "</p>");
        out.println("<a class='btn btn-primary' id='info-login-link' href='login.jsp'>Go to Login</a>");
        out.println("</section></main></body></html>");
    }

    /** Writes one statistic tile. */
    private static void stat(PrintWriter out, String label, String value) {
        out.println("<div class='stat'><span class='stat-label'>" + label
                + "</span><span class='stat-value'>" + value + "</span></div>");
    }

    /** Minimal HTML escaping for text that comes from outside our code. */
    private static String escape(String s) {
        return s == null ? "" : s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    /** Called once when Tomcat unloads the servlet. */
    @Override
    public void destroy() {
        log("BankInfoServlet destroyed");
    }
}
